# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-08-08 18:45
=======
# Generated by Django 1.11.4 on 2017-08-09 15:00
>>>>>>> 2c697d8a57a707ef45fc27c3e68b6071407bed53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
<<<<<<< HEAD
                ('numero_factura', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=b'Num factura')),
                ('empresa', models.CharField(default=b'-', max_length=200)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(choices=[(b'Pagado', b'Pagado'), (b'Pendiente', b'Pendiente'), (b'Acumulado', b'Acumulado')], default=b'acumulado', max_length=25)),
=======
                ('numero_factura', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Num factura')),
                ('empresa', models.CharField(default='-', max_length=200)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Acumulado', 'Acumulado')], default='acumulado', max_length=25)),
>>>>>>> 2c697d8a57a707ef45fc27c3e68b6071407bed53
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
<<<<<<< HEAD
                ('numero_recibo', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=b'nun recibo')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(default=b' ', max_length=200)),
                ('concepto', models.CharField(default=b' ', max_length=200)),
=======
                ('numero_recibo', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='nun recibo')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(default=' ', max_length=200)),
                ('concepto', models.CharField(default=' ', max_length=200)),
>>>>>>> 2c697d8a57a707ef45fc27c3e68b6071407bed53
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
