# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=b'Num factura')),
                ('empresa', models.CharField(default=b'-', max_length=200)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(choices=[(b'Pagado', b'Pagado'), (b'Pendiente', b'Pendiente'), (b'Acumulado', b'Acumulado')], default=b'acumulado', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('numero_recibo', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=b'nun recibo')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(default=b' ', max_length=200)),
                ('concepto', models.CharField(default=b' ', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
