# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_mvc', '0002_auto_20170728_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[(b'0', b'Pagado'), (b'1', b'Pendiente'), (b'2', b'Acumulado')], default=b'acumulado', max_length=25),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=b'Num factura'),
        ),
    ]
